### ISSUE TITLE
adding aws_session_token to config

### ISSUE THREAD

**Issue by Vzzarr** [crowemi/target-s3#11]
To access AWS it is sometimes requested to use an aws_session_token as well.

I forked:
https://github.com/Vzzarr/target-s3/commit/25e556ad5b9725074207561e80d24ecbbe260cb0

`                aws_session_token=aws_config.get("aws_session_token", None),
`

and this is working for me.
Would you please consider adding this to the code base or allow me to create a branch to PR?

**Comment by crowemi** [comment]
@Vzzarr -- I'd prefer if you made the changes and submitted a PR. Perhaps I don't have the repo configured correctly 🤔

**Comment by crowemi** [comment]
I think the issue may be that you need to create a branch on your end as `main` is protected 🤷‍♂️

**Comment by Vzzarr** [comment]
@crowemi more than happy to raise a PR can you grant me permission to create a new branch?
I run the following locally
```
➜  target-s3 git:(main) git checkout -b add-aws-session-token
Switched to a new branch 'add-aws-session-token'
➜  target-s3 git:(add-aws-session-token) git push origin add-aws-session-token 
ERROR: Permission to crowemi/target-s3.git denied to Vzzarr.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Let me know if that is ok with you

**Comment by crowemi** [comment]
@Vzzarr, thank you for your patience 🙃 - I think this is supposed to be done from your fork: create a new branch off your fork then create a PR from that branch back into the main repo. If that doesn't work I'll set you up as collaborator. I just don't want to (and shouldn't) have to do that for everyone that wants to contribute. Again, I may be missing a setting on the repo.

**Comment by Vzzarr** [comment]
@crowemi my bad, this is actually my first time I fork and PR and didn't know that was possible.
But there you go:
https://github.com/crowemi/target-s3/pull/12
Let me know if anything else is needed

**Comment by Vzzarr** [comment]
@crowemi One more thing I wanted to raise, I configured this target via Meltano and I had to create the following:
```
    config:
      prefix: $S3_KEY
      format:
        format_type: json
      cloud_provider:
        cloud_provider_type: aws
        aws:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
          aws_region: $AWS_DEFAULT_REGION
          aws_session_token: $AWS_SESSION_TOKEN
          aws_bucket: $S3_BUCKET
```

But using the `meltano config target-s3 set aws_access_key $AWS_ACCESS_KEY_ID` as per https://hub.meltano.com/loaders/target-s3/ it didn't add params like `cloud_provider`, `cloud_provider_type` or `aws`. 
I had to manually add them after many tests and reading through the code base.
But maybe this can be addressed in a different PR, just wanted to raise my experience to your attention.
