### ISSUE TITLE
Format jsonl not working

### ISSUE THREAD

**Issue by dror-g** [crowemi/target-s3#37]
Hi, tried setting the format to jsonl like so:
```
format:
  format_type: jsonl
  format_parquet:
    validate: false
```

Got immediate error:
`'jsonl' is not a valid choice for 'format.format_type'`

Using Meltano Docker image [latest](https://hub.docker.com/layers/meltano/meltano/latest/images/sha256-dee699e476c57d9c6577c50260f921f9883ab361d71d562c8599986c3ffc11cf?context=explore)

Thanks for all your hard work!!!
